
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Part2.src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 10;
  public static final int PREFIX = 13;
  public static final int EOF = 0;
  public static final int PLUS = 7;
  public static final int STRING = 3;
  public static final int IF = 4;
  public static final int ELSE = 5;
  public static final int ID = 2;
  public static final int COMMA = 12;
  public static final int error = 1;
  public static final int SEMICOLON = 15;
  public static final int RPAREN = 9;
  public static final int DEF = 6;
  public static final int SUFFIX = 14;
  public static final int RBRACE = 11;
  public static final int LPAREN = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "STRING",
  "IF",
  "ELSE",
  "DEF",
  "PLUS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "COMMA",
  "PREFIX",
  "SUFFIX",
  "SEMICOLON"
  };
}

